name: avoid
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.0
  mailer: ^6.0.1
  bcrypt: ^1.1.3
  permission_handler: ^11.3.1
  image_picker: ^1.0.0
  json_annotation: ^4.8.1

  flutter_polyline_points: ^2.0.1 
  flutter_compass: ^0.8.0  
  auto_size_text: ^3.0.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  http: ^1.2.1
  provider: ^6.1.2
  dio: ^5.4.0
  google_maps_flutter: ^2.6.1

  geodesy: ^0.4.0
  vector_math: ^2.1.4
  flutter_tts: ^4.0.2

  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  uuid: ^4.3.3
  flutter_typeahead: ^5.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/avoid_logo.png
    - assets/images/motor_logo.png
    - assets/images/placeholder.png
    - assets/images/logo2.png
    - assets/images/avoid_app_logo.png
    - assets/images/avoid_app_logo_nobg.png
    - assets/images/nav_arrow.png
    - assets/images/floods_icon.png
    - assets/images/weather_icon.png
    - floods_datasets/rizal_floodprone_areas.csv
    - floods_datasets/flood_testing_capstone.csv
    - alert_dataset/rizal_pedestrian_zones_merged.geojson
    - alert_dataset/pedestrians_test.geojson
    - alert_dataset/rizal_no_overtaking_zone.geojson
    - alert_dataset/no_overtaking_zone_test.geojson

  fonts:
    - family: Judson
      fonts:
        - asset: assets/fonts/Judson-Regular.ttf
        - asset: assets/fonts/Judson-Italic.ttf
        - asset: assets/fonts/Judson-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/images/avoid_app_logo_nobg.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/avoid_app_logo_nobg.png
